spring:
  config:
    name: spia-cam
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: NON_NULL
  kafka:
     producer:
#       bootstrap-servers: 172.25.10.49:9092
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
     consumer:
        bootstrap-servers: localhost:9092
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer